/// <reference types="nativewind/types" />
import 'nativewind/types';
// NOTE: Thisimport 'nativewind/types'; file should not be edited and should be committed with your source code. It is generated by NativeWind.